#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

echo "* Setup irc home"
groupadd -g 1100 irc
useradd -m -s /usr/bin/bash -d /home/irc -u 1100 -g irc irc
passwd -N irc
passwd -d irc

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
